skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rxtrail = "Hv1GvjSSoF4naRh7wduFJ8x4dJi3E9W3VJ2u544uLrYC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
