# Generated by Django 6.1.2 on 2026-10-06 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_chainbinding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionrecord",
            name="prescriber",
            field=models.CharField(db_index=True, default="", max_length=63),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("prescriber", "Prescriber"),
                            ("dispenser", "Dispenser"),
                            ("professional_authority", "Professional authority"),
                            ("health_authority", "Health authority"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("key_name", models.CharField(blank=True, max_length=63)),
                ("display_name", models.CharField(max_length=200)),
                ("license_number", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("summary", models.CharField(max_length=300)),
                ("prescription_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("signature", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="records.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
