# Generated by Django 6.1.2 on 2026-10-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_prescriptionrecord_prescriber_participant_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("medication_id", models.CharField(max_length=64, unique=True)),
                ("address", models.CharField(max_length=64, unique=True)),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("active_ingredient", models.CharField(max_length=200)),
                ("strength", models.CharField(max_length=64)),
                ("form", models.CharField(max_length=64)),
                ("atc_code", models.CharField(blank=True, db_index=True, max_length=7)),
                ("unit", models.CharField(default="unit", max_length=32)),
                ("regulatory_list", models.CharField(blank=True, max_length=16)),
                ("dosage_guidance", models.TextField(blank=True)),
                ("usual_max_daily_units", models.PositiveIntegerField(blank=True, null=True)),
                ("max_quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("max_validity_days", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("country", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="participant",
            name="role",
            field=models.CharField(
                choices=[
                    ("prescriber", "Prescriber"),
                    ("dispenser", "Dispenser"),
                    ("professional_authority", "Professional authority"),
                    ("health_authority", "Health authority"),
                    ("catalog_authority", "Catalog authority"),
                    ("auditor", "Auditor"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CatalogProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_id", models.CharField(max_length=64, unique=True)),
                ("address", models.CharField(max_length=64, unique=True)),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("brand_name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reference", "Reference"),
                            ("generic", "Generic"),
                            ("similar", "Similar"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="records.catalogmedication",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="records.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["brand_name"],
            },
        ),
    ]
