# Generated by Django 6.1.2 on 2026-10-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0005_prescriptionrecord_patient_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionrecord",
            name="closure_note",
            field=models.TextField(blank=True),
        ),
    ]
